FROM alpine:latest

RUN echo http://mirrors.ustc.edu.cn/alpine/v3.7/main/  > /etc/apk/repositories \
    && echo http://mirrors.ustc.edu.cn/alpine/v3.7/community/  >> /etc/apk/repositories \
    && apk update \
    && apk upgrade \
    && wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 \
    && tar -xjf phantomjs-2.1.1-linux-x86_64.tar.bz2 \
    && cd phantomjs-2.1.1-linux-x86_64 \
